### ISSUE TITLE
[BUG] broken button/font layout on the main github page

### ISSUE THREAD

**Issue by yolando-carwell** [SAP/btp-solution-diagrams#55]
### Main area of the  BTP Solution Diagrams that is affected?

Other

### Steps to reproduce

When visiting https://sap.github.io/btp-solution-diagrams/, I see that some button labels are "broken". I attach a screen shot for the details (There are three buttons with "broken" labels). I am using a Mac. The issue exists both on Safari and Firefox.

<img width="1024" alt="Screenshot 2024-04-10 at 15 45 12" src="https://github.com/SAP/btp-solution-diagrams/assets/162127438/5b502f5c-ff0a-415a-be79-e3fbd5e283a2">

### Desired behavior

Button labels should neither wrap, nor be cut-off.

**Comment by Visua-Liza** [comment]
We saw this earlier but it seems to be fixed now: 
![Screenshot 2024-04-15 at 11 41 13](https://github.com/SAP/btp-solution-diagrams/assets/152990597/1516f07c-7d7f-4613-b415-6873a5874a2f)

**Comment by Visua-Liza** [comment]
fixed for now, thanks for the heads-up

**Comment by yolando-carwell** [comment]
Sorry, but I still see the same issue, so it is only fixed for _some_ visitors. Don't hesitate to contact me via Teams in case you want to analyze it in my environment.
